version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.13.1
  commands:
    - echo "Installing dependencies..."
    - yarn install
    - npm install -g @vue/cli@4.5.13
  
  build:
    commands:
      - echo "Building project..."
      - yarn generate
  
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/ s3://test-nuxt-s3 --delete